name: Flutter Tests

on:
  push:
    branches:
      - master # Puedes cambiar esto al nombre de tu rama principal

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.10.0'

      with:
        flutter-version: 'stable' # Puedes cambiar esto a la versión que necesites

    - name: Get Dependencies
      run: flutter pub get
